AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PlantUML Serverless API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Metadata:
  AWS::ServerlessRepo::Application:
    Name: plantuml-render
    Description: PlantUML Serverless API and UI
    Author: mmajis
    SpdxLicenseId: GPL-3.0-only
    LicenseUrl: s3://plantuml-serverlessrepo/LICENSE
    ReadmeUrl: s3://plantuml-serverlessrepo/README.md
    Labels: ['plantuml']
    HomePageUrl: https://github.com/mmajis/plantuml-serverless
    SemanticVersion: 0.0.9
    SourceCodeUrl: https://github.com/mmajis/plantuml-serverless/releases/tag/v0.0.9

Resources:
  PlantUMLAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: plantuml
      DefinitionBody:
          swagger: 2.0
          info:
            title:
              Ref: AWS::StackName
          paths:
            "/":
              get: 
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UIFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
            "/uml/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UmlFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
            "/png/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PngFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
            "/img/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ImgFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
            "/svg/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SvgFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
            "/txt/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TxtFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
            "/map/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MapFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
            "/check/{encodedUml}":
              get:
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: 200
                  uri:
                    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SyntaxFunction.Arn}/invocations"
                  httpMethod: POST
                  type: aws_proxy
                  contentHandling: CONVERT_TO_BINARY
          x-amazon-apigateway-binary-media-types:
            - "*/*"
  UIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.UIHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

  UmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.UmlHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /uml/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI

  PngFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.PngHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /png/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

  ImgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.PngHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /img/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

  SvgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.SvgHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /svg/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

  TxtFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.TxtHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /txt/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile
            
  MapFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.MapHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /map/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

  SyntaxFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: [ "com.nitor.plantuml.lambda.SyntaxHandler::handleRequest" ]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /check/{encodedUml}
            Method: get
            RestApiId: !Ref PlantUMLAPI
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub "https://${PlantUMLAPI}.execute-api.${AWS::Region}.amazonaws.com/plantuml"
  ExampleDiagram:
    Description: Example URL to render a PlantUML diagram
    Value: !Sub "https://${PlantUMLAPI}.execute-api.${AWS::Region}.amazonaws.com/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000"
